### ISSUE TITLE
Can't build image

### ISSUE THREAD

**Issue by SemenMartynov** [staslovelas/xml-val-xsd#1]
```
[INFO] Building Docker context /media/basket/home/Documents/SPbPU/SEseminars/students/xml-val-xsd
[INFO] 
[INFO] Image will be built as springio/xml-xsd-validation:latest
[INFO] 
[INFO] Step 1/8 : FROM openjdk:8-jdk-alpine
[INFO] 
[INFO] Pulling from library/openjdk
[INFO] Image 4fe2ade4980c: Already exists
[INFO] Image 6fc58a8d4ae4: Pulling fs layer
[INFO] Image ef87ded15917: Pulling fs layer
[INFO] Image 6fc58a8d4ae4: Downloading
[INFO] Image 6fc58a8d4ae4: Download complete
[INFO] Image 6fc58a8d4ae4: Extracting
[INFO] Image 6fc58a8d4ae4: Pull complete
[INFO] Image ef87ded15917: Downloading
[INFO] Image ef87ded15917: Verifying Checksum
[INFO] Image ef87ded15917: Download complete
[INFO] Image ef87ded15917: Extracting
[INFO] Image ef87ded15917: Pull complete
[INFO] Digest: sha256:b18e45570b6f59bf80c15c78d7f0daff1e18e9c19069c323613297057095fda6
[INFO] Status: Downloaded newer image for openjdk:8-jdk-alpine
[INFO]  ---> 97bc1352afde
[INFO] Step 2/8 : VOLUME /tmp
[INFO] 
[INFO]  ---> Running in 3803158df131
[INFO] Removing intermediate container 3803158df131
[INFO]  ---> 51746d374ae2
[INFO] Step 3/8 : ARG DEPENDENCY=target/dependency
[INFO] 
[INFO]  ---> Running in 6d3dc84dc49b
[INFO] Removing intermediate container 6d3dc84dc49b
[INFO]  ---> 9a75a80c7f1c
[INFO] Step 4/8 : COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
[INFO] 
[ERROR] COPY failed: stat /var/lib/docker/tmp/docker-builder163042217/target/dependency/BOOT-INF/lib: no such file or directory
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:208)
	at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:110)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:259)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:248)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.spotify.docker.client.exceptions.DockerException: COPY failed: stat /var/lib/docker/tmp/docker-builder163042217/target/dependency/BOOT-INF/lib: no such file or directory
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
	at com.spotify.docker.client.DefaultDockerClient$BuildProgressHandler.progress(DefaultDockerClient.java:305)
	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:77)
	at com.spotify.docker.client.DefaultDockerClient$ResponseTailReader.call(DefaultDockerClient.java:2734)
	at com.spotify.docker.client.DefaultDockerClient$ResponseTailReader.call(DefaultDockerClient.java:2718)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[INFO] Building Docker context /media/basket/home/Documents/SPbPU/SEseminars/students/xml-val-xsd
[INFO] 
[INFO] Image will be built as springio/xml-xsd-validation:latest
[INFO] 
[INFO] Step 1/8 : FROM openjdk:8-jdk-alpine
[INFO] 
[INFO] Pulling from library/openjdk
[INFO] Digest: sha256:b18e45570b6f59bf80c15c78d7f0daff1e18e9c19069c323613297057095fda6
[INFO] Status: Image is up to date for openjdk:8-jdk-alpine
[INFO]  ---> 97bc1352afde
[INFO] Step 2/8 : VOLUME /tmp
[INFO] 
[INFO]  ---> Using cache
[INFO]  ---> 51746d374ae2
[INFO] Step 3/8 : ARG DEPENDENCY=target/dependency
[INFO] 
[INFO]  ---> Using cache
[INFO]  ---> 9a75a80c7f1c
[INFO] Step 4/8 : COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
[INFO] 
[ERROR] COPY failed: stat /var/lib/docker/tmp/docker-builder625622217/target/dependency/BOOT-INF/lib: no such file or directory
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:17 min
[INFO] Finished at: 2018-12-20T00:10:20+03:00
[INFO] Final Memory: 40M/137M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.9:build (default) on project xml-xsd-validation: Could not build image: COPY failed: stat /var/lib/docker/tmp/docker-builder625622217/target/dependency/BOOT-INF/lib: no such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by chertpaderi** [comment]
Fixed
